name: Build and Release EXE

on:
  push:
    tags:
      - 'v*.*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp pyinstaller upx matplotlib seaborn pillow

      - name: Download UPX
        run: |
          Invoke-WebRequest https://github.com/upx/upx/releases/download/v4.2.1/upx-4.2.1-win64.zip -OutFile upx.zip
          Expand-Archive upx.zip -DestinationPath upx
          echo "UPX dir: $(Get-ChildItem upx)"

      - name: Build with PyInstaller & UPX
        run: |
          pyinstaller --noconfirm --onefile --windowed ^
            --icon=app_icon.ico ^
            --name MediaToolkitApp ^
            MediaToolkitApp.py ^
            --upx-dir upx/upx-4.2.1-win64

      - name: Zip executable to avoid antivirus false positives
        run: |
          Compress-Archive -Path dist/MediaToolkitApp.exe -DestinationPath MediaToolkitApp_v${{ github.ref_name }}.zip

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: MediaToolkitApp_v${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
